export type GrupoEtp = "Informações Básicas" | "Necessidade" | "Solução" | "Planejamento" | "Viabilidade" | "Anexos";
export type CampoEtp = { chave:string; grupo:GrupoEtp; titulo:string; pergunta:string; explicacao:string; fundamento:string; obrigatorio:boolean; origem:"servidor"|"lex"|"mista"; evidencias?:string[]; opcoes?:string[] };

export const CAMPOS_ETP: CampoEtp[] = [
 {chave:"areaRequisitante",grupo:"Informações Básicas",titulo:"Área requisitante",pergunta:"Qual é a **área requisitante** e, se houver, qual área técnica participa do planejamento?",explicacao:"Informe órgão, secretaria, setor, unidade ou equipe que identificou a necessidade. O LEX reaproveita o cadastro quando houver.",fundamento:"IN SEGES 58/2022, arts. 3º e 8º",obrigatorio:false,origem:"servidor"},
 {chave:"necessidade",grupo:"Necessidade",titulo:"Descrição da necessidade",pergunta:"Vamos consolidar a **necessidade sob a perspectiva do interesse público**. Há algo a complementar no problema já identificado?",explicacao:"O texto deve demonstrar situação atual, problema, impacto e resultado esperado; não apenas repetir o objeto.",fundamento:"IN SEGES 58/2022, art. 9º, I",obrigatorio:true,origem:"mista",evidencias:["DFD","relatórios","chamados","inventário","consumo","demanda das unidades"]},
 {chave:"requisitosContratacao",grupo:"Necessidade",titulo:"Requisitos da contratação",pergunta:"Quais **requisitos mínimos e suficientes** a solução precisa atender?",explicacao:"Inclua desempenho, qualidade, normas, sustentabilidade e manutenção/assistência quando aplicável, sem restringir competição sem justificativa.",fundamento:"IN SEGES 58/2022, art. 9º, II e §2º",obrigatorio:false,origem:"mista"},
 {chave:"levantamentoMercado",grupo:"Solução",titulo:"Levantamento de mercado",pergunta:"Quer que o LEX faça o **levantamento de mercado** e compare alternativas de solução?",explicacao:"O LEX pesquisa contratações semelhantes e alternativas técnicas/logísticas; você confirma o que faz sentido para o órgão.",fundamento:"IN SEGES 58/2022, art. 9º, III e art. 12",obrigatorio:false,origem:"lex",opcoes:["Pesquisar alternativas automaticamente","Já tenho alternativas para informar","Pesquisar e depois eu confirmo"],evidencias:["ETPs de outras unidades","PNCP","Compras.gov","contratações anteriores","consulta ao mercado"]},
 {chave:"descricaoSolucao",grupo:"Solução",titulo:"Descrição da solução como um todo",pergunta:"Considerando a necessidade e as alternativas, como deve ser a **solução como um todo**?",explicacao:"Inclua componentes, integração, manutenção e assistência técnica quando aplicável; a solução deve decorrer do levantamento de mercado.",fundamento:"IN SEGES 58/2022, art. 9º, IV",obrigatorio:false,origem:"mista"},
 {chave:"quantidade",grupo:"Solução",titulo:"Estimativa das quantidades",pergunta:"Confirma a **quantidade a contratar** identificada na DFD ou deseja ajustar?",explicacao:"A quantidade precisa de memória de cálculo e documentos: consumo, usuários, estoque, expansão, substituição, histórico ou outra base concreta.",fundamento:"IN SEGES 58/2022, art. 9º, V",obrigatorio:true,origem:"mista"},
 {chave:"justificativaQuantitativo",grupo:"Solução",titulo:"Memória de cálculo do quantitativo",pergunta:"Qual é a **memória de cálculo** que sustenta esse quantitativo?",explicacao:"O LEX reaproveita a DFD e pede apenas o que faltar; documentos de suporte ficam vinculados em Anexos.",fundamento:"IN SEGES 58/2022, art. 9º, V",obrigatorio:true,origem:"mista",evidencias:["série histórica","estoque","inventário","número de usuários","demanda projetada","contratação anterior"]},
 {chave:"estimativaValor",grupo:"Solução",titulo:"Estimativa do valor da contratação",pergunta:"Quer usar a **estimativa já pesquisada pelo LEX** ou complementar com outras referências?",explicacao:"Registrar preços unitários, memória de cálculo e documentos de suporte. O LEX cruza Compras.gov/PNCP e mantém a trilha das fontes.",fundamento:"IN SEGES 58/2022, art. 9º, VI; Lei 14.133/2021, art. 23",obrigatorio:true,origem:"lex",opcoes:["Usar pesquisa oficial do LEX","Adicionar outras referências","Revisar a estimativa antes"]},
 {chave:"parcelamento",grupo:"Solução",titulo:"Parcelamento ou não da solução",pergunta:"A solução deve ser **parcelada por itens/lotes** ou contratada de forma conjunta?",explicacao:"O LEX compara competitividade, divisibilidade técnica, integração e economia de escala antes de sugerir a justificativa.",fundamento:"IN SEGES 58/2022, art. 9º, VII; Lei 14.133/2021, art. 40",obrigatorio:true,origem:"mista",opcoes:["Parcelar por item","Parcelar por lote","Contratação conjunta","Quero que o LEX analise"]},
 {chave:"correlatas",grupo:"Solução",titulo:"Contratações correlatas e interdependentes",pergunta:"Existe alguma contratação **correlata ou interdependente** que precisa ser considerada?",explicacao:"O LEX pode procurar processos anteriores, mas a unidade confirma dependência operacional real.",fundamento:"IN SEGES 58/2022, art. 9º, VIII",obrigatorio:false,origem:"mista",opcoes:["Sim, existem","Não existem","Não sei — procurar no histórico"]},
 {chave:"alinhamentoPlanejamento",grupo:"Planejamento",titulo:"Alinhamento com o planejamento",pergunta:"Como essa contratação está alinhada ao **PCA, PLS ou outro instrumento de planejamento**?",explicacao:"O LEX nunca afirma previsão no PCA sem confirmação; se não houver previsão, registra justificativa e providência.",fundamento:"IN SEGES 58/2022, arts. 7º e 9º, IX",obrigatorio:false,origem:"servidor",opcoes:["Prevista no PCA","Prevista em outro planejamento","Não está prevista — justificar","Preciso verificar"]},
 {chave:"resultadosPretendidos",grupo:"Planejamento",titulo:"Resultados pretendidos",pergunta:"Quais **ganhos concretos** o órgão espera obter?",explicacao:"Considere economicidade, eficiência, eficácia e melhor aproveitamento dos recursos humanos, materiais e financeiros.",fundamento:"IN SEGES 58/2022, art. 9º, X",obrigatorio:false,origem:"mista"},
 {chave:"providencias",grupo:"Planejamento",titulo:"Providências prévias",pergunta:"Há alguma **providência que precisa acontecer antes do contrato**?",explicacao:"Ex.: adequar ambiente, obter licença/autorização, preparar infraestrutura ou capacitar gestor e fiscais.",fundamento:"IN SEGES 58/2022, art. 9º, XI",obrigatorio:false,origem:"mista",opcoes:["Não há providência especial","Adequação do ambiente","Licença/autorização","Capacitação de gestor/fiscais","Outra"]},
 {chave:"impactosAmbientais",grupo:"Planejamento",titulo:"Impactos ambientais e sustentabilidade",pergunta:"Há **impactos ambientais ou requisitos de sustentabilidade** aplicáveis?",explicacao:"Quando aplicável, considere energia/recursos, logística reversa, reciclagem, descarte e medidas mitigadoras.",fundamento:"IN SEGES 58/2022, art. 9º, XII",obrigatorio:false,origem:"mista",opcoes:["Há impactos a tratar","Não identifico impacto relevante","Quero que o LEX sugira pontos para validar"]},
 {chave:"viabilidade",grupo:"Viabilidade",titulo:"Posicionamento conclusivo sobre a viabilidade",pergunta:"Com base no estudo, a contratação é **adequada e viável** para atender à necessidade?",explicacao:"O LEX prepara a conclusão com necessidade, alternativas, mercado, quantidade, valor e planejamento; você confirma a decisão.",fundamento:"IN SEGES 58/2022, art. 9º, XIII",obrigatorio:true,origem:"mista",opcoes:["Viável","Viável com condicionantes","Não viável","Quero que o LEX faça a análise conclusiva"]},
 {chave:"responsaveis",grupo:"Informações Básicas",titulo:"Responsáveis pelo ETP",pergunta:"Quem são os **responsáveis pela elaboração e revisão/aprovação** deste ETP?",explicacao:"O LEX pode aproveitar usuários/equipe cadastrados. Dados pessoais só aparecem quando exigidos pelo fluxo aplicável.",fundamento:"IN SEGES 58/2022, art. 8º",obrigatorio:false,origem:"servidor"},
 {chave:"anexosEtp",grupo:"Anexos",titulo:"Anexos e documentos de suporte",pergunta:"Quer **anexar ou vincular** documentos que comprovam o ETP?",explicacao:"Memórias de cálculo, pesquisas, cotações, inventários, relatórios, ETPs similares e demais evidências devem ficar na trilha do processo.",fundamento:"IN SEGES 58/2022, art. 9º, V e VI",obrigatorio:false,origem:"servidor",opcoes:["Anexar arquivo","Usar documentos já vinculados","Continuar e anexar depois"]}
];

export const GRUPOS_ETP: GrupoEtp[] = ["Informações Básicas","Necessidade","Solução","Planejamento","Viabilidade","Anexos"];
export function camposEtpConversa(){ return CAMPOS_ETP.map(({chave,pergunta,explicacao,opcoes,grupo,fundamento})=>({chave,pergunta,explicacao,opcoes,grupo,fundamento})); }
export function guiaEtpParaIA(){ return GRUPOS_ETP.map(grupo=>`## ${grupo}\n`+CAMPOS_ETP.filter(c=>c.grupo===grupo).map(c=>`- ${c.titulo} [${c.obrigatorio?"mínimo obrigatório":"avaliar/justificar se não aplicável"}] — ${c.fundamento}. Origem: ${c.origem}.`).join("\n")).join("\n\n"); }
